# Generated by Django 5.0.1 on 2024-01-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField()),
                ('crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.classlist')),
            ],
        ),
    ]
