# Generated by Django 5.0.1 on 2024-01-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_offerings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerings',
            name='days',
        ),
    ]
