# Generated by Django 5.0.1 on 2024-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_days_times_offeringdays_offeringtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='end',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='times',
            name='start',
            field=models.TextField(),
        ),
    ]
